##
## Copyright (c) 2015 Tamir Duberstein
## All rights reserved.
##
## This file is distributed under the University of Illinois Open Source
## License.  See the file COPYING for details.
##

###############################################################################

language: cpp

before_install:
  - sudo scripts/travis_deps.sh

script: CXX=/usr/lib/llvm-3.6/bin/clang++ ./configure --with-llvm=/usr/lib/llvm-3.6 && make -j2
