##
## Copyright (c) 2015, 2016, 2017, 2018 The University of Utah
## Copyright (c) 2015 Tamir Duberstein
## All rights reserved.
##
## This file is distributed under the University of Illinois Open Source
## License.  See the file COPYING for details.
##

###############################################################################

sudo: required
dist: xenial
language: cpp

before_install:
  - sudo scripts/travis_deps.sh

script: >
  CXX=/usr/lib/llvm-6.0/bin/clang++
  CC=/usr/lib/llvm-6.0/bin/clang
  ./configure --with-llvm=/usr/lib/llvm-6.0 &&
  make -j2 &&
  make check

###############################################################################

## End of file.
